-- Inserindo novo logradouro
INSERT INTO BRH.ENDERECO
(CEP, UF, CIDADE, BAIRRO)
VALUES ('08223080','SP','SAO PAULO','CID A E CARVALHO');

-- Inserindo novo colaborador
INSERT INTO BRH.COLABORADOR
(MATRICULA, CPF, NOME, SALARIO, DEPARTAMENTO, CEP, LOGRADOURO, COMPLEMENTO_ENDERECO)
VALUES ('A124', '147.115.927-43', 'Fulano De Tal', 12000.00, 'DEPTI', '71444-400', 'Avenida Principal' , 'CASA');

-- Inserido  projeto
INSERT INTO BRH.PROJETO
(ID, NOME, RESPONSAVEL, INICIO, FIM)
VALUES (5, 'BI', 'A124','14/05/2024','31/12/2024');

-- Inserido  papel
INSERT INTO BRH.PAPEL
(ID, NOME)
VALUES (8, 'Especialista de Negocios');

-- Inserido  celular
INSERT INTO BRH.TELEFONE_COLABORADOR
(NUMERO, COLABORADOR, TIPO)
VALUES ('(61) 9 9999-9999','A124','C'); -- Celular

-- Inserido  residencial 
INSERT INTO BRH.TELEFONE_COLABORADOR
(NUMERO, COLABORADOR, TIPO)
VALUES ('(61) 3030-4040','A124','C'); -- Celular

-- Inserido  email
INSERT INTO BRH.Email_COLABORADOR
(EMAIL, COLABORADOR, TIPO)
VALUES ('fulano@email.com','A124','P'); -- Pessoal

-- Inserido  email trabalho 
INSERT INTO BRH.EMAIL_COLABORADOR
(EMAIL, COLABORADOR, TIPO)
VALUES ('fulano.tal@brh.com','A124','T'); -- Trabalho

-- Inserido  dependente filho
INSERT INTO BRH.DEPENDENTE
(CPF, NOME, DATA_NASCIMENTO, PARENTESCO, COLABORADOR)
VALUES ('999.999.999.99', 'Beltrana de Tal', '01/05/2020', 'Filho(a)', 'A124');

-- Inserido  esposa
INSERT INTO BRH.DEPENDENTE
(CPF, NOME, DATA_NASCIMENTO, PARENTESCO, COLABORADOR)
VALUES ('111.111.111.11', 'Cicrana de Tal', '20/07/1993', 'CÃ´njuge', 'A124');



-- Relatório cônjuges
SELECT 
    C.MATRICULA,
    D.NOME AS NOME_DEPENDENTE,
    D.DATA_NASCIMENTO AS DATA_NASCIMENTO_DEPENDENTE
FROM 
    BRH.DEPENDENTE D INNER JOIN BRH.COLABORADOR C ON C.MATRICULA = D.COLABORADOR 
WHERE 
    D.PARENTESCO = 'CÃ´njuge';


-- Relatório de contatos telefônicos
SELECT
    C.NOME
    ,TC.COLABORADOR
    ,TC.NUMERO
    ,TC.TIPO
FROM
    BRH.TELEFONE_COLABORADOR TC INNER JOIN BRH.COLABORADOR C ON TC.COLABORADOR = C.MATRICULA
WHERE
    TIPO = 'M' OR TIPO = 'C'
ORDER BY COLABORADOR, NUMERO;

-- Listar colaborador com maior salário
SELECT
    NOME
    ,(SALARIO)
FROM
    BRH.COLABORADOR
WHERE SALARIO = (SELECT MAX (SALARIO) FROM BRH.COLABORADOR);

SELECT * FROM BRH.TELEFONE_COLABORADOR;
SELECT * FROM BRH.COLABORADOR;

